### ISSUE TITLE
How to recompile gx-go

### ISSUE THREAD

**Issue by leinue** [whyrusleeping/gx-go#60]
I am compiling filecoin which occurs this error:

``` shell
ERROR: Error: package 'go-filecoin' requires at least go version 1.11.1.
however, your gx-go binary was compiled with go1.9.2.
Please update gx-go (or recompile with your current go compiler)
ERROR: req-check hook failed: exit status 1 
```

I'm not a go developer and don't know how to recompile gx-go.
I have run `go build` in source folder of gx-go which didn't work.

Can any help me with this ?

**Comment by schomatis** [comment]
Use [`go install`](https://golang.org/cmd/go/#hdr-Compile_and_install_packages_and_dependencies).

We should be matching the Go terminology in this error message.

**Comment by leinue** [comment]
Deleting all the go file and retry can be succeed.
